name: Publish NuGet Packages

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: dotnet test
  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Build
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack -c Release -o build

      - name: Publish NuGet Packages to GitHub
        run: dotnet nuget push ./build/*.nupkg --skip-duplicate --no-symbols true -s https://nuget.pkg.github.com/erictuvesson/index.json -k ${{ secrets.GITHUB_TOKEN }}

      - name: Publish NuGet Packages to NuGet
        run: dotnet nuget push ./build/*.nupkg --skip-duplicate --no-symbols true -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}
